DATASET:
  PATH:
    TFRECORDS : '/home/thanhho/SPARC/ESCA/Code/Data/Target-20230127T101110Z-001/Target/intersection/Target1/tfrecord' 
    NORMAL : '/home/thanhho/SPARC/ESCA/Code/Data/Target-20230127T101110Z-001/Target/intersection/Target1/normal' 
    ANOMALY : '/home/thanhho/SPARC/ESCA/Code/Data/Target-20230127T101110Z-001/Target/intersection/Target1/abnormal'
    # TEST: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Normal'

TRAINING: 
  SAVE_PATH : '/home/thanhho/SPARC/ESCA/Code/Data/audio_44.1k-20230127T101044Z-001/Results'
  EPOCH : 75

TRANSFER_LEARNING: 
  NORMAL_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord/train'
  ANOMALY_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/tfrecord/anomaly'
  BASED_WEIGHTS: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/Results/saved_model/vq_vae'
  SAVE_PATH: './Results/'

RECORD: 
  DEVICE_INDEX_INPUT: 18
  ABNOMALY: True
  SECOND: 5
  DATASET_PATH: './dataset'