DATASET:
  PATH:
    TFRECORDS : ['/home/sparclab/ESCA/ThanhHo/tfrecord/source' ]
    NORMAL : '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/VQ-VAE_on_PC/training_on_pc/Data/park/normal'
    ANOMALY : '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/VQ-VAE_on_PC/training_on_pc/Data/park/anomaly'
    # TEST: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Normal'

TRAINING: 
  SAVE_PATH : '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/D-ESCA_v2/Results/base_training'
  EPOCH : 75

TRANSFER_LEARNING: 
  EPOCH : 200
  TFRECORDS : ['/home/sparclab/ESCA/ThanhHo/tfrecord/target']
  BASED_WEIGHTS: '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/D-ESCA_v2/Results/base_training/saved_model/vq_vae'
  SAVE_PATH: '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/D-ESCA_v2/Results/tl-training'

REALTIME: 
  DEVICE_INDEX_INPUT: 18
  LOG_PATH: '/home/thanhho/SPARC/ESCA/Github/IoT-AnomallySoundDetection/D-ESCA_v2/Results/rt_test_results'
  TRANSFER_LEARNING: True

RECORD: 
  DEVICE_INDEX_INPUT: 18
  ABNOMALY: True
  SECOND: 2
  DATASET_PATH: './dataset'

DEVICE:
  JETSON: False