DATASET:
  PATH:
    TFRECORDS : './test/tfrecord' 
    NORMAL : '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/VQ-VAE_on_PC/training_on_pc/Data/target/park/Target3/normal' 
    ANOMALY : '/home/sparclab/ESCA/ThanhHo/temp/IoT-AnomallySoundDetection/VQ-VAE_on_PC/training_on_pc/Data/target/park/Target3/anomaly'
    # TEST: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Normal'

TRAINING: 
  SAVE_PATH : '/home/thanhho/SPARC/ESCA/Github/IoT-AnomallySoundDetection/D-ESCA_v2/Results/base-training_results'
  EPOCH : 200

TRANSFER_LEARNING: 
  EPOCH : 2
  NORMAL_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/park_demo/tfrecord_target_park/train'
  ANOMALY_DATA_DIRS: '/home/thanhho/SPARC/ESCA/Code/Data/park_demo/tfrecord_target_park/anomaly'
  BASED_WEIGHTS: '/home/thanhho/SPARC/ESCA/Github/IoT-AnomallySoundDetection/D-ESCA_v2/Results/base-training_results/saved_model/vq_vae'
  SAVE_PATH: '/home/thanhho/SPARC/ESCA/Github/IoT-AnomallySoundDetection/D-ESCA_v2/Results/tl-training_results'

REALTIME: 
  DEVICE_INDEX_INPUT: 18
  LOG_PATH: '/home/thanhho/SPARC/ESCA/Github/IoT-AnomallySoundDetection/D-ESCA_v2/Results/rt_test_results'
  TRANSFER_LEARNING: True

RECORD: 
  DEVICE_INDEX_INPUT: 18
  ABNOMALY: True
  SECOND: 2
  DATASET_PATH: './dataset'

DEVICE:
  JETSON: False