DATASET:
  PATH:
    TFRECORDS : ['./park_dataset_demo/source','./park_dataset_demo/target/Target1','./park_dataset_demo/target/Target2']
    NORMAL : '/home/thanhho/SPARC/ESCA/Code/training_on_pc/Data/target/park/Target1/normal'
    ANOMALY : '/home/thanhho/SPARC/ESCA/Code/training_on_pc/Data/target/park/Target1/anomaly'
    # TEST: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Normal'

TRAINING: 
  SAVE_PATH : './Results/base_training'
  EPOCH : 75

TRANSFER_LEARNING: 
  EPOCH : 81
  TFRECORDS : ['./park_dataset_demo/target/Target3']
  BASED_WEIGHTS: './Results/tl-training_results/Target2/saved_model/vq_vae'
  SAVE_PATH: './Results/tl-training_results/Target3'
REALTIME: 
  DEVICE_INDEX_INPUT: 18
  LOG_PATH: './Results/rt_test_results'
  TRANSFER_LEARNING: True
  #IMPORT_FILE : True
  # MANUAL_THRESHOLD: 0.0

RECORD: 
  DEVICE_INDEX_INPUT: 14
  ABNOMALY: True
  SECOND: 5
  DATASET_PATH: './dataset_mic_usb_16k'
  SAMPLING_RATE: 16000

DEVICE:
  JETSON: True
